// ============================================================================
// Pull Skill Tree — From Dead Hang to Muscle-Up
// ============================================================================
// Dead Hang → Scapular Pull → Australian → Neg. Pull-up → Pull-up → Chin-up
// → L-Sit Pull-up → Muscle-up
// Equipment: bar (park, playground, doorframe pull-up bar ~$15)
// ============================================================================

import type { SkillNode } from '../../models';
import { createDefaultProgress } from '../../models';

export const PULL_TREE_NODES: SkillNode[] = [
  {
    id: 'pull_dead_hang',
    name: 'Dead Hang',
    description:
      'Hang from a bar with straight arms. Relax your shoulders. Breathe. This decompresses your spine, builds grip strength, and is the foundation of ALL pulling movements. Do this every single day.',
    category: 'pull',
    exerciseType: 'hold',
    minimumTier: 0,
    equipment: ['bar'],
    formCues: ['straight arms', 'relaxed shoulders', 'deep breaths', 'full grip'],
    prerequisites: [],
    masteryThreshold: { sets: 3, holdSeconds: 30, consecutiveDays: 3 },
    expPerSet: 10,
    masteryBonusExp: 150,
    status: 'unlocked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_scapular',
    name: 'Scapular Pull-up',
    description:
      'From a dead hang, pull your shoulder blades DOWN and TOGETHER without bending your elbows. This micro-movement activates your lats and teaches scapular control — the secret to all advanced pulling.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 0,
    equipment: ['bar'],
    formCues: ['straight arms throughout', 'pull scapulae down', 'chest rises slightly', 'slow and deliberate'],
    prerequisites: [{ nodeId: 'pull_dead_hang', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 15, consecutiveDays: 3 },
    expPerSet: 12,
    masteryBonusExp: 200,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_australian',
    name: 'Australian Pull-up',
    description:
      'Inverted row — hang under a low bar (playground, table edge, sturdy railing) with feet on the ground. Pull chest to bar. The lower the bar, the harder it is. Progressive and accessible.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 0,
    equipment: ['bar'],
    formCues: ['straight body', 'chest to bar', 'squeeze shoulder blades', 'controlled descent'],
    prerequisites: [{ nodeId: 'pull_scapular', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 20, consecutiveDays: 3 },
    expPerSet: 15,
    masteryBonusExp: 250,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_negative',
    name: 'Negative Pull-up',
    description:
      'Jump or step up to the top of a pull-up position. Lower yourself down as SLOWLY as possible (5-10 seconds). This builds the eccentric strength needed for full pull-ups. The slowdown is the workout.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 1,
    equipment: ['bar'],
    formCues: ['start at top', '5-10 second descent', 'fight gravity', 'full dead hang at bottom'],
    prerequisites: [{ nodeId: 'pull_australian', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 8, consecutiveDays: 5 },
    expPerSet: 20,
    masteryBonusExp: 400,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_chinup',
    name: 'Chin-up',
    description:
      'Underhand (supinated) grip, shoulder width. Pull chin over the bar. Chin-ups recruit more biceps than pull-ups and are typically easier to learn first. No ego — use what works.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 1,
    equipment: ['bar'],
    formCues: ['underhand grip', 'chin over bar', 'full dead hang at bottom', 'no kipping'],
    prerequisites: [{ nodeId: 'pull_negative', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 10, consecutiveDays: 5 },
    expPerSet: 25,
    masteryBonusExp: 500,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_pullup',
    name: 'Pull-up',
    description:
      'Overhand (pronated) grip, slightly wider than shoulders. Pull chin over bar from a dead hang. No kipping, no swinging. Clean reps only. This is the gold standard of bodyweight pulling.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 2,
    equipment: ['bar'],
    formCues: ['overhand grip', 'dead hang start', 'chin over bar', 'no kipping', 'controlled descent'],
    prerequisites: [{ nodeId: 'pull_chinup', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 10, consecutiveDays: 5 },
    expPerSet: 25,
    masteryBonusExp: 600,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_wide',
    name: 'Wide Pull-up',
    description:
      'Hands 1.5× shoulder width. Greater lat activation. Harder than standard pull-ups — a sign of real back strength.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 2,
    equipment: ['bar'],
    formCues: ['wide grip', 'pull to upper chest', 'squeeze lats', 'full extension at bottom'],
    prerequisites: [{ nodeId: 'pull_pullup', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 8, consecutiveDays: 3 },
    expPerSet: 28,
    masteryBonusExp: 500,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_lsit_pullup',
    name: 'L-Sit Pull-up',
    description:
      'Pull-up with legs extended forward at 90° (L-position). Combines pulling strength with core strength. If you can do these, you\'re dangerous.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 3,
    equipment: ['bar'],
    formCues: ['legs at 90°', 'toes pointed', 'full pull-up ROM', 'maintain L throughout'],
    prerequisites: [{ nodeId: 'pull_pullup', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 8, consecutiveDays: 5 },
    expPerSet: 35,
    masteryBonusExp: 800,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_typewriter',
    name: 'Typewriter Pull-up',
    description:
      'Pull up, then shift side-to-side at the top while maintaining chin over bar. Builds the unilateral strength needed for one-arm pull-up progression.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 3,
    equipment: ['bar'],
    formCues: ['pull to top', 'shift laterally', 'chin stays over bar', 'controlled'],
    prerequisites: [
      { nodeId: 'pull_wide', requireMastery: true },
      { nodeId: 'pull_lsit_pullup', requireMastery: true },
    ],
    masteryThreshold: { sets: 3, reps: 5, consecutiveDays: 5 },
    expPerSet: 35,
    masteryBonusExp: 1000,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'pull_muscle_up',
    name: 'Muscle-up',
    description:
      'The holy grail of bar work. Pull up AND over the bar in one fluid motion, transitioning from pull to dip. This separates the trained from the elite. The move Anatoly does casually while people stare.',
    category: 'pull',
    exerciseType: 'reps',
    minimumTier: 4,
    equipment: ['bar'],
    formCues: ['explosive pull', 'false grip helps', 'lean forward at transition', 'full dip lockout at top'],
    prerequisites: [{ nodeId: 'pull_typewriter', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 3, consecutiveDays: 5 },
    expPerSet: 50,
    masteryBonusExp: 2000,
    status: 'locked',
    progress: createDefaultProgress(),
  },
];

export const PULL_MAIN_PATH = [
  'pull_dead_hang',
  'pull_scapular',
  'pull_australian',
  'pull_negative',
  'pull_chinup',
  'pull_pullup',
  'pull_lsit_pullup',
  'pull_muscle_up',
];
