// ============================================================================
// Push Skill Tree — Progressive Push Mastery
// ============================================================================
// Wall → Incline → Knee → Standard → Diamond → Archer → One-Arm Push-up
// Equipment: wall, elevated surface (bench/stairs), floor — all free
// ============================================================================

import type { SkillNode } from '../../models';
import { createDefaultProgress } from '../../models';

export const PUSH_TREE_NODES: SkillNode[] = [
  {
    id: 'push_wall',
    name: 'Wall Push-up',
    description:
      'Stand arm\'s length from a wall. Place palms flat, lower chest to wall, push back. Focus on scapular control and full range of motion. This is where everyone starts — no shame, only progress.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 0,
    equipment: ['wall'],
    formCues: ['elbows 45°', 'full ROM', 'squeeze chest at top', 'controlled tempo'],
    prerequisites: [],
    masteryThreshold: { sets: 3, reps: 50, consecutiveDays: 3 },
    expPerSet: 10,
    masteryBonusExp: 150,
    status: 'unlocked', // Root node — always available
    progress: createDefaultProgress(),
  },
  {
    id: 'push_incline',
    name: 'Incline Push-up',
    description:
      'Hands on a bench, stairs, or any elevated surface. The lower the surface, the harder it gets. Use stairs to micro-progress — start at step 5, work down to step 1.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 0,
    equipment: ['elevated_surface'],
    formCues: ['straight body line', 'core tight', 'chest to surface', 'no hip sag'],
    prerequisites: [{ nodeId: 'push_wall', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 30, consecutiveDays: 3 },
    expPerSet: 15,
    masteryBonusExp: 200,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_knee',
    name: 'Knee Push-up',
    description:
      'Full push-up position but with knees on the ground. Cross your ankles. This bridges the gap between incline and full push-ups. Don\'t rush past this — build the pattern.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 0,
    equipment: ['none'],
    formCues: ['hips in line with shoulders', 'full chest to floor', 'slow negative'],
    prerequisites: [{ nodeId: 'push_incline', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 25, consecutiveDays: 3 },
    expPerSet: 15,
    masteryBonusExp: 250,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_standard',
    name: 'Standard Push-up',
    description:
      'The king of bodyweight pushing. Hands shoulder-width, straight line from head to heels, chest touches floor, full lockout at top. Master this and you\'ve earned your Initiate stripe.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 1,
    equipment: ['none'],
    formCues: ['elbows 45°', 'core braced', 'chest to floor', 'full lockout', '2s down, 1s up'],
    prerequisites: [{ nodeId: 'push_knee', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 20, consecutiveDays: 5 },
    expPerSet: 20,
    masteryBonusExp: 400,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_wide',
    name: 'Wide Push-up',
    description:
      'Hands 1.5× shoulder width. Emphasizes chest over triceps. A lateral branch that builds pushing endurance and chest strength.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 1,
    equipment: ['none'],
    formCues: ['wide hand placement', 'elbows flare naturally', 'full ROM'],
    prerequisites: [{ nodeId: 'push_standard', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 20, consecutiveDays: 3 },
    expPerSet: 20,
    masteryBonusExp: 300,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_diamond',
    name: 'Diamond Push-up',
    description:
      'Hands together forming a diamond shape under chest. Devastating for triceps. If you can do 15 of these, your pushing strength is no joke.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 2,
    equipment: ['none'],
    formCues: ['diamond hand position', 'elbows tight to body', 'chest to hands', 'slow eccentric'],
    prerequisites: [{ nodeId: 'push_standard', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 15, consecutiveDays: 5 },
    expPerSet: 25,
    masteryBonusExp: 500,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_pike',
    name: 'Pike Push-up',
    description:
      'Hips high in an inverted V. Targets shoulders heavily — the gateway to handstand push-ups. Use this to build overhead pressing strength with zero equipment.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 2,
    equipment: ['none'],
    formCues: ['hips high', 'head between arms', 'head to floor', 'press straight up'],
    prerequisites: [{ nodeId: 'push_standard', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 15, consecutiveDays: 5 },
    expPerSet: 25,
    masteryBonusExp: 500,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_decline',
    name: 'Decline Push-up',
    description:
      'Feet elevated on a bench or stairs. Increases the load on upper chest and shoulders. The higher the feet, the harder it gets.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 2,
    equipment: ['elevated_surface'],
    formCues: ['feet elevated', 'straight body line', 'chest to floor', 'controlled'],
    prerequisites: [{ nodeId: 'push_standard', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 15, consecutiveDays: 3 },
    expPerSet: 22,
    masteryBonusExp: 400,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_archer',
    name: 'Archer Push-up',
    description:
      'One arm pushes while the other extends to the side for balance. This is the stepping stone to one-arm push-ups. Pure unilateral pushing power.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 3,
    equipment: ['none'],
    formCues: ['working arm does 90% of work', 'extend assist arm fully', 'alternate sides', 'slow and controlled'],
    prerequisites: [
      { nodeId: 'push_diamond', requireMastery: true },
      { nodeId: 'push_wide', requireMastery: true },
    ],
    masteryThreshold: { sets: 3, reps: 10, consecutiveDays: 5 },
    expPerSet: 30,
    masteryBonusExp: 800,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_handstand',
    name: 'Wall Handstand Hold',
    description:
      'Kick up to a handstand against a wall. Hold. This builds insane shoulder stability and overhead strength. Start with chest-to-wall for safety.',
    category: 'push',
    exerciseType: 'hold',
    minimumTier: 3,
    equipment: ['wall'],
    formCues: ['chest to wall', 'arms locked', 'core tight', 'look at floor between hands'],
    prerequisites: [{ nodeId: 'push_pike', requireMastery: true }],
    masteryThreshold: { sets: 3, holdSeconds: 30, consecutiveDays: 5 },
    expPerSet: 30,
    masteryBonusExp: 800,
    status: 'locked',
    progress: createDefaultProgress(),
  },
  {
    id: 'push_one_arm',
    name: 'One-Arm Push-up',
    description:
      'The final boss of pushing. One hand behind your back. Feet wide for balance. If you can do 5 clean reps, you are in the top 1% of bodyweight strength. Sleeper territory.',
    category: 'push',
    exerciseType: 'reps',
    minimumTier: 4,
    equipment: ['none'],
    formCues: ['wide feet', 'non-working hand behind back', 'minimal torso rotation', 'full ROM'],
    prerequisites: [{ nodeId: 'push_archer', requireMastery: true }],
    masteryThreshold: { sets: 3, reps: 5, consecutiveDays: 5 },
    expPerSet: 40,
    masteryBonusExp: 1500,
    status: 'locked',
    progress: createDefaultProgress(),
  },
];

export const PUSH_MAIN_PATH = [
  'push_wall',
  'push_incline',
  'push_knee',
  'push_standard',
  'push_diamond',
  'push_archer',
  'push_one_arm',
];
